services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
      - node_modules_data:/var/www/html/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:3vuI/Jx//H2jNJ7VF2eRdcXCbATCx13C+E8+REDSxqw=
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cuanto_sabe_db
      DB_USERNAME: CuantoSabe
      DB_PASSWORD: CuantoSabe2025!
      LOG_CHANNEL: stack
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      PUSHER_HOST: ""
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
    command: php artisan serve --host=0.0.0.0 --port=8080

  db:
    image: mariadb:10.11
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuanto_sabe_db
      MYSQL_USER: CuantoSabe
      MYSQL_PASSWORD: CuantoSabe2025!
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  dbdata:
  vendor_data:
  node_modules_data: