version: "3.9"

services:
  app:
    image: lcebreiros/cuantosabe:latest
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "80:8080"  # Exponemos en puerto 80 para HTTP
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_NAME: "Juego Cuanto Sabe"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:3vuI/Jx//H2jNJ7VF2eRdcXCbATCx13C+E8+REDSxqw=
      APP_URL: https://app.cuantosabe.com.ar
      
      # Database
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3307
      DB_DATABASE: cuanto_sabe_db
      DB_USERNAME: CuantoSabe
      DB_PASSWORD: CuantoSabe2025!
      
      # Session y Cache
      SESSION_DRIVER: database
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: "false"
      SESSION_SECURE_COOKIE: "true"
      CACHE_DRIVER: database
      
      # Pusher
      BROADCAST_CONNECTION: pusher
      BROADCAST_DRIVER: pusher
      PUSHER_APP_ID: 2019775
      PUSHER_APP_KEY: b6ac4842db4cad2e2c14
      PUSHER_APP_SECRET: 726404c507a2de730933
      PUSHER_APP_CLUSTER: sa1
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
      
      # Queue y logs
      QUEUE_CONNECTION: database
      LOG_CHANNEL: stderr
      LOG_LEVEL: error
      
      # Vite variables
      VITE_PUSHER_APP_KEY: b6ac4842db4cad2e2c14
      VITE_PUSHER_APP_CLUSTER: sa1
      VITE_PUSHER_PORT: 443
      VITE_PUSHER_SCHEME: https
    
    volumes:
      - storage_data:/var/www/html/storage/app
      - storage_logs:/var/www/html/storage/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - app-network

  db:
    image: mariadb:10.11
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuanto_sabe_db
      MYSQL_USER: CuantoSabe
      MYSQL_PASSWORD: CuantoSabe2025!
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"  # Solo para debug, remover en producción
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

volumes:
  dbdata:
    driver: local
  storage_data:
    driver: local
  storage_logs:
    driver: local

networks:
  app-network:
    driver: bridge