version: "3.9"

services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    # SIN volúmenes (código dentro de la imagen)
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:3vuI/Jx//H2jNJ7VF2eRdcXCbATCx13C+E8+REDSxqw=
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cuanto_sabe_db
      DB_USERNAME: CuantoSabe
      DB_PASSWORD: CuantoSabe2025!
      LOG_CHANNEL: stderr             # Logs a Docker
      SESSION_DRIVER: database        # Sesiones en DB
      CACHE_DRIVER: database          # Cache en DB
    networks:
      - app-network

  db:
    image: mariadb:10.11
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuanto_sabe_db
      MYSQL_USER: CuantoSabe
      MYSQL_PASSWORD: CuantoSabe2025!
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge